### PR TITLE
Use environment variables configuration

### PR DESCRIPTION
**Pull request by garcianavalon**
Hi!

I am creating this PR to propose a change on how to deal with configuration. Instead of having a template file and a out-of-vc copy of the file I propose using a base file with defaults that can be overrided with environment variables.

This change makes installations easier, increases the portability of the code and works much better with VMs and container technologies like Docker.

What do you think?

### CODE REVIEW

**Comment by aalonsog** [comment]
Hi Enrique,
the main reason of having config template file is to put the main config file out of version control. With your solution, if I introduce changes in the configuration file, they will be tracked by version control. This is a behavior we want to avoid.

**Comment by garcianavalon** [comment]
Hi Álvaro,

That is a very reasonable concern but that doesn't happen with the system I am proposing.

The new base file is identical to the current existing template file. The difference is, instead of overriding the whole file with a copy, environment variables override specific settings. Because env variables are not files but shell session specific data they will never get in a version control system.

With the old system, to change a single setting a new file is needed(we need the file even just to use the default settings!), which is very cumbersome in ephemeral environments like VMs and containers. On the other hand, env variables are easily pass around, flexible and simple. Another argument for env variables is that they are an industry standard.

**Comment by aalonsog** [comment]
Ok, I misunderstood you. I though you were thinking on the possibility of overwriting the config file (apart of the option of using env vars). 

Then, I prefer to implement the possibility of using command line parameters as we do in Licode (for example in [erizoController](https://github.com/ging/licode/blob/master/erizo_controller/erizoController/erizoController.js#L73) ). What do you think?

**Comment by garcianavalon** [comment]
I see, that could be a good option too. Why do you prefer it?
To be sure l understand, it will me something like node `ackuaria.js --whatever-option`, isn't it?

**Pull request closed without merging**
