### PR TITLE
add basic installation instructions

### PR DESCRIPTION
**Pull request by thehunmonkgroup**

### CODE REVIEW

**Comment by nachoaguadoc** [comment]
Hi, thank you very much for the installation guide. However, you're missing a step. Before running the server, it's necessary to copy the compiled file of Nuve  ("licode/nuve/nuveClient/dist/nuve.js") to the path "ackuaria/nuve.js". Can you add that step to I can perform the merge?

Thanks

Best Regards

**Comment by thehunmonkgroup** [comment]
At this time, I don't think that step is needed, as the repository already includes a complied nuve.js:

https://github.com/ging/ackuaria/blob/master/nuve.js

Seems like it would be a different pull request to change that?

**Comment by nachoaguadoc** [comment]
After the last commit nuve.js has been removed from the project, it's important that the user compiles its own file when installing Ackuaria. It was a mistake by my part uploading it, because it needs to be the same version as the Licode version the user has installed.

**Comment by thehunmonkgroup** [comment]
ok, i added the stop you requested, let me know if you need anything else

**Comment by nachoaguadoc** [comment]
Merged, thank you very much!

**Pull request merged**
